### ISSUE TITLE
Fix integration tests for MacOS and Windows runners

### ISSUE THREAD

**Issue by tvandinther** [tvandinther/libsql-client-dotnet#16]
The integration tests uses docker compose to create a libsql server to test against. The MacOS and Windows runners no longer come with docker installed so these tests fail to run.

**Comment by s-e-f** [comment]
Attempting to pick this up. It looks like docker is installed on the agent but since its Windows, it only supports Windows-based images. I believe the same problem exists on regular docker use in Windows.

Perhaps this can be solved by using a Windows agent that has docker configured for WSL? I'm not sure about Mac though...

**Comment by tvandinther** [comment]
After a brief search I think it could be worth exploring the WSL option. WSL2 doesn't seem to be supported yet but could be soon, so hopefully it can still work.

For MacOS it might just need brew install of the docker software components required in a previous step.

**Comment by tvandinther** [comment]
I'm going to try a proof of concept using [test containers](https://dotnet.testcontainers.org/) instead of docker compose.

**Comment by tvandinther** [comment]
#23 is open. I have decided to skip tests requiring containers on platforms that don't support virtualisation on GitHub-hosted runners (Windows & macOS). I figure that running these extra tests on just Linux is sufficient along with a disclaimer in the README.
